### ISSUE TITLE
Add support for Qt 5

### ISSUE THREAD

**Issue by JinShil** [Dav1dde/lumen#10]
I can't seem to use Lumen this with the latest version of KDE, but I'd really love to.  It was my a staple of my D development for about a year.

**Comment by Dav1dde** [comment]
This is on my TODO for quite a while now, unfortunatly I don't have that much time. I try to get it in in my summer break.

**Comment by Dav1dde** [comment]
Just some news on this, the new version is ready, I posted the patch to the reviewboard, https://git.reviewboard.kde.org/r/124190/

You can find the diff on the review board if you want to build Kate/Kdevelop from source with the plugin.
