### ISSUE TITLE
Add support for compiling using Clang

### ISSUE THREAD

**Issue by jamadagni** [Dav1dde/lumen#11]
Hello. I use Clang for my default C/C++ compiler. As a result of this, if I try compiling lumen using the normal procedure (`mkdir build ; cd build ; cmake ../lumen/ ; make`) I get the following errors:

```
Scanning dependencies of target ktexteditor_lumen_automoc
Generating dcd.moc
/home/samjnaa/sr/_repos/git/dlang--lumen/lumen/dcd.h:90: Note: No relevant classes found. No output generated.
Generating lumen.moc
Generating completion.moc
[  0%] Built target ktexteditor_lumen_automoc
Scanning dependencies of target ktexteditor_lumen
[ 25%] Building CXX object CMakeFiles/ktexteditor_lumen.dir/ktexteditor_lumen_automoc.o
[ 50%] Building CXX object CMakeFiles/ktexteditor_lumen.dir/lumen.o
[ 75%] Building CXX object CMakeFiles/ktexteditor_lumen.dir/dcd.o
/home/samjnaa/sr/_repos/git/dlang--lumen/lumen/dcd.cpp:27:36: warning: use of enumeration in a nested name specifier is a C++11 extension
    [-Wc++11-extensions]
char DCDCompletionItemType::toChar(DCDCompletionItemType::DCDCompletionItemType e)
                                ^
/home/samjnaa/sr/_repos/git/dlang--lumen/lumen/dcd.cpp:27:36: error: no type named 'DCDCompletionItemType' in
    'DCDCompletionItemType::DCDCompletionItemType'; did you mean simply 'DCDCompletionItemType'?
char DCDCompletionItemType::toChar(DCDCompletionItemType::DCDCompletionItemType e)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                DCDCompletionItemType
/home/samjnaa/sr/_repos/git/dlang--lumen/lumen/dcd.h:31:10: note: 'DCDCompletionItemType' declared here
    enum DCDCompletionItemType {
        ^
1 warning and 1 error generated.
CMakeFiles/ktexteditor_lumen.dir/build.make:100: recipe for target 'CMakeFiles/ktexteditor_lumen.dir/dcd.o' failed
make[2]: *** [CMakeFiles/ktexteditor_lumen.dir/dcd.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/ktexteditor_lumen.dir/all' failed
make[1]: *** [CMakeFiles/ktexteditor_lumen.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2
```

However, if I use GCC there are no errors. IIUC the only thing required to support Clang seems to be an explicit selection of C++11 using the -std=c++11 somewhere in the CMake files. As I am not experienced with CMake I am not able to submit a patch or pull request. Please fix this.

Thanks for Lumen!

**Comment by Dav1dde** [comment]
Actually if you have Kdevelop or Kate installed Lumen is already available, just enable it in your extensions settings. The code doesn't work with current Kdevelop/Kate git master (KDE 5), but I have a KDE5 version in review since yesterday.

Also this Repository is dead, the current changes are all in the KDE git (I should make that clear).

Regarding the error, I don't know why this happens and how to fix it properly, since the makefile is actually called by Kate/Kdevelop build "framework".

**Comment by jamadagni** [comment]
OK thanks -- I found Lumen under KDevelop > Settings > Configure Editor > Extensions. I guess I didn't need to clone this repo then. Please make it clear on the Readme.MD file that this repo is no longer used.

On an aside, can you clarify whether the Lumen plugin will automatically load the DCD server if available or should I add a command to auto-start that upon KDE session startup somewhere? ([This page](https://github.com/Hackerpilot/DCD) says "for now it must be started manually or by an editor plugin.")

**Comment by Dav1dde** [comment]
The plugin will try to launch a server with `dcd-server`, on the default port, which will fail if there is already a server running on this port. So the server already running is choosen.

I actually recommend running your own server.

See: https://github.com/Dav1dde/lumen#dcd-server
